spring:
  application:
    name: bumblebee

feign:
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: application/json, text/csv
    response:
      enabled: true
  connectTimeout: 5000
  readTimeout: 5000
